[platformio]
src_dir = firmware
default_envs = modem_bridge

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:modem_bridge]
build_src_filter = +<modem_bridge.cpp>

[env:connectivity_test]
build_src_filter = +<connectivity_test.cpp>
